export const STR = {
  zhHant: {
    homeGreeting: '嗨，準備好了嗎？', startShopping: '開始購物', settings: 'EN / 中', parentShort: '家長', chooseLang: '選擇語言',
    missionLabel: '任務', missionTitle: '幫我買這幾樣！', shoppingList: '購物清單', missionCount: '5 樣', go: '出發購物',
    listToBuy: '要買清單', checkout: '去結帳',
    cartTitle: '一起算算看！', confirmAmount: '確認金額',
    amountDue: '應付金額', trayLabel: '付款盤', paidIn: '已放入', change: '找零', wallet: '錢包', takeChange: '收下找零', unit: '× 1',
    paid: '付款', playAgain: '再買一次', backHome: '回首頁',
    zDrinks: '飲料區', zSnacks: '零食區', zCandy: '糖果區', zFrozen: '冷凍區', zHot: '熱食區',
    itOrange: '橙汁', itChips: '薯片', itLolli: '棒棒糖', itIcepop: '雪條', itHotdog: '熱狗',
    pWater: '礦泉水', pOrange: '橙汁', pMilk: '牛奶', pJuiceBox: '果汁盒',
    pChips: '薯片', pBiscuit: '餅乾', pPopcorn: '爆米花', pPretzel: '百力滋',
    pLolli: '棒棒糖', pFruitCandy: '水果糖', pGummy: '軟糖', pChoco: '巧克力',
    pIceCup: '雪糕杯', pIcepop: '雪條', pFrozenPizza: '冷凍薄餅', pFrozenDim: '冷凍點心',
    pHotdog: '熱狗', pBun: '包點', pOden: '關東煮', pNuggets: '炸雞塊',
    parentTitle: '家長中心', latestSession: '上次遊戲',
    pDate: '日期', pDuration: '時長', pLevel: '難度', levelEasy: '初級', levelIntermediate: '中級', levelHard: '高級',
    calcAccuracy: '計算正確率', payAccuracy: '付款正確率', confusedDenoms: '易混淆面額', stampHistory: '集點進度',
    digestTitle: '課後摘要通知', digestSub: '電郵摘要', noSessions: '尚無遊戲記錄',
    calcHint: '將所有價格加起來！', payHint: '點擊鈔幣付款',
  },
  zhHans: {
    homeGreeting: '嗨，准备好了吗？', startShopping: '开始购物', settings: 'EN / 中', parentShort: '家长', chooseLang: '选择语言',
    missionLabel: '任务', missionTitle: '帮我买这几样！', shoppingList: '购物清单', missionCount: '5 样', go: '出发购物',
    listToBuy: '要买清单', checkout: '去结账',
    cartTitle: '一起算算看！', confirmAmount: '确认金额',
    amountDue: '应付金额', trayLabel: '付款盘', paidIn: '已放入', change: '找零', wallet: '钱包', takeChange: '收下找零', unit: '× 1',
    paid: '付款', playAgain: '再买一次', backHome: '回首页',
    zDrinks: '饮料区', zSnacks: '零食区', zCandy: '糖果区', zFrozen: '冷冻区', zHot: '热食区',
    itOrange: '橙汁', itChips: '薯片', itLolli: '棒棒糖', itIcepop: '雪条', itHotdog: '热狗',
    pWater: '矿泉水', pOrange: '橙汁', pMilk: '牛奶', pJuiceBox: '果汁盒',
    pChips: '薯片', pBiscuit: '饼干', pPopcorn: '爆米花', pPretzel: '百力滋',
    pLolli: '棒棒糖', pFruitCandy: '水果糖', pGummy: '软糖', pChoco: '巧克力',
    pIceCup: '雪糕杯', pIcepop: '雪条', pFrozenPizza: '冷冻薄饼', pFrozenDim: '冷冻点心',
    pHotdog: '热狗', pBun: '包点', pOden: '关东煮', pNuggets: '炸鸡块',
    parentTitle: '家长中心', latestSession: '上次游戏',
    pDate: '日期', pDuration: '时长', pLevel: '难度', levelEasy: '初级', levelIntermediate: '中级', levelHard: '高级',
    calcAccuracy: '计算正确率', payAccuracy: '付款正确率', confusedDenoms: '易混淆面额', stampHistory: '集点进度',
    digestTitle: '课后摘要通知', digestSub: '电邮摘要', noSessions: '尚无游戏记录',
    calcHint: '将所有价格加起来！', payHint: '点击钞币付款',
  },
  en: {
    homeGreeting: 'Hi! Ready to go shopping?', startShopping: 'Start Shopping', settings: 'EN / 中', parentShort: 'Parent', chooseLang: 'Choose Language',
    missionLabel: 'Mission', missionTitle: 'Help me buy these!', shoppingList: 'Shopping List', missionCount: '5 items', go: "Let's Go!",
    listToBuy: 'To Buy', checkout: 'Checkout',
    cartTitle: "Let's add it up!", confirmAmount: 'Confirm Amount',
    amountDue: 'Amount Due', trayLabel: 'PAYMENT TRAY', paidIn: 'Paid In', change: 'Change', wallet: 'Wallet', takeChange: 'Take Change', unit: '× 1',
    paid: 'Paid', playAgain: 'Play Again', backHome: 'Home',
    zDrinks: 'Drinks', zSnacks: 'Snacks', zCandy: 'Candy', zFrozen: 'Frozen', zHot: 'Hot Food',
    itOrange: 'Orange Juice', itChips: 'Potato Chips', itLolli: 'Lollipop', itIcepop: 'Ice Pop', itHotdog: 'Hot Dog',
    pWater: 'Water', pOrange: 'Orange Juice', pMilk: 'Milk', pJuiceBox: 'Juice Box',
    pChips: 'Potato Chips', pBiscuit: 'Biscuits', pPopcorn: 'Popcorn', pPretzel: 'Pretzels',
    pLolli: 'Lollipop', pFruitCandy: 'Fruit Candy', pGummy: 'Gummies', pChoco: 'Chocolate',
    pIceCup: 'Ice Cream Cup', pIcepop: 'Ice Pop', pFrozenPizza: 'Frozen Pizza', pFrozenDim: 'Frozen Dim Sum',
    pHotdog: 'Hot Dog', pBun: 'Steamed Bun', pOden: 'Oden', pNuggets: 'Chicken Nuggets',
    parentTitle: 'Parent Dashboard', latestSession: 'Latest Session',
    pDate: 'Date', pDuration: 'Duration', pLevel: 'Level', levelEasy: 'Easy', levelIntermediate: 'Intermediate', levelHard: 'Hard',
    calcAccuracy: 'Calculation Accuracy', payAccuracy: 'Payment Accuracy', confusedDenoms: 'Most-confused Denominations', stampHistory: 'Stamp-card History',
    digestTitle: 'Post-session Digest', digestSub: 'Email digest', noSessions: 'No sessions yet — play a round!',
    calcHint: 'Add up all the prices!', payHint: 'Tap money to pay',
  },
};
